apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: manual
  name: nginx-4
  labels:
    app: nginx-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-4
  template:
    metadata:
      labels:
        app: nginx-4
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
