apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3
  labels:
    app: nginx-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
      labels:
        app: nginx-3
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
